### ISSUE TITLE
Document athena tx format

### ISSUE THREAD

**Issue by lrettig** [athenavm/athena#172]
TX := VERSION + PRINCIPAL + METADATA + PAYLOAD + SIGNATURE
VERSION := 1 (u8, SCALE-encoded)
PRINCIPAL := [u8; 24] (address, SCALE-encoded)
METADATA := NONCE + GAS_PRICE
NONCE := u64, SCALE-encoded
GAS_PRICE := u64, SCALE-encoded
SIGNATURE := [u8; 64] (ed25519 signature of the raw tx not including the signature)

PAYLOAD is opaque to the host (go-spacemesh) and is variable length.

PAYLOAD := METHOD_SELECTOR + ARGS
METHOD_SELECTOR := [u8; 4]

ARGS depends on the method:

## Spawn

ARGS := PUBKEY
PUBKEY := [u8; 32]

## Spend

ARGS := RECIPIENT + AMOUNT
RECIPIENT := [u8; 24] (address, SCALE-encoded)
AMOUNT := u64, SCALE-encoded

**Comment by lrettig** [comment]
CC @poszu @brusherru

**Comment by lrettig** [comment]
I added a simple test vector generator: https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/cmd/gen/main.go

Attaching sample output:

[vectors.txt](https://github.com/user-attachments/files/17532250/vectors.txt)

**Comment by brusherru** [comment]
Some clarifications:
- VERSION is encoded using Compact codec, and currently supported only version `1` which is encoded as `Byte(4)` or `Hex("04")`: https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/vm.go#L482-L489
- NONCE and GAS_PRICE are encoded by Compact codec as well

@lrettig If I'm wrong, please correct me

**Comment by brusherru** [comment]
However it is not clear to me how exactly encoded method selector and template address (if it is used?).
I took the first example from `vestors.txt` and disassembled it, but there are 7 bytes that I don't understand how encoded... Could you clarify it please?

```
Version (Compact): 04
Principal (Bytes(24)): 00000000a6c709f0b839433263da9b046115bd6fb672914d
Meta:
- Nonce (Compact): 00
- GasPrice (Compact): 04
Payload:
- ????: 980103f53f2080 <-- How it is encoded?
- PubKey (Bytes(32)):53a2a936d14e49d97ded8df45371dd9c0fd035f71565e69a4eb101c60cc9801d
Signature (Bytes(64)): 09820b32974ea0eb8160833b04a93ebad4f940b83b0f168069a55596db21d03bfd2025ca5a7b05fbb23302003e5ea3489a82868e961e964d1bd9bdd211a3b108
```

**Comment by lrettig** [comment]
VERSION, NONCE, and GAS_PRICE are all SCALE-encoded. I'm not intricately familiar with the details of SCALE (e.g., how compact codec works). VERSION works the same way as in Spacemesh today. NONCE and GAS_PRICE are encoded from this data type: https://github.com/spacemeshos/go-spacemesh/blob/29bf0e3f0cf9cfda7f2de36be7d0d9c34aa7e5e3/vm/core/types.go#L144-L148.

Tx encoding happens here: https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/sdk/wallet/tx.go. Here is the main encode: https://github.com/spacemeshos/go-spacemesh/blob/29bf0e3f0cf9cfda7f2de36be7d0d9c34aa7e5e3/vm/sdk/wallet/tx.go#L60. Note that, for now, we leave out genesisID (but it will be added later).

You can also refer to the program used to generate the test vectors: https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/cmd/gen/main.go

Regarding the Athena payload, take a look at how it's done in the vm sdk:

- https://github.com/spacemeshos/go-spacemesh/blob/29bf0e3f0cf9cfda7f2de36be7d0d9c34aa7e5e3/vm/sdk/wallet/tx.go#L53
- https://github.com/spacemeshos/go-spacemesh/blob/29bf0e3f0cf9cfda7f2de36be7d0d9c34aa7e5e3/vm/sdk/wallet/tx.go#L85

Under the hood, this also uses SCALE to combine the method selector and method args together into the payload:

https://github.com/athenavm/athena/blob/815cd53d397b5b936c97c6e89bce962f41abb8dc/vm/sdk/src/wallet.rs#L22-L43

If you create the same data structure and SCALE-encode it, you'll get the same serialized bytes.

Let me know if it's still unclear.

**Comment by poszu** [comment]
I think there are multiple issues, on both sides.

@brusherru you seem to misdecoded gas price. A compact-encoded gas price = `0x04` decodes to value `1`, not `4` (see https://docs.substrate.io/reference/scale-codec/ there is exactly this example)

@lrettig I found two issues in the vectors.txt
- the method selector in the first column is created from wrong method names (`athcon_spawn/spend` instead of `athexp_spawn/spend`)
- the TX payload is encoded twice in:
  ```go
  athenaPayload := vmlib.EncodeTxSpawn(athcon.Bytes32(signing.Public(pk)))
  // basically a type cast `type Payload []byte`
  payload := core.Payload(athenaPayload)
  tx := encode(&sdk.TxVersion, &principal, &meta, &payload)
  ```
 
  The `payload` is already a `[]byte` and is scale-encoded for the second time resulting in `980103f53f20808ab114d8af564b468686fef13c8554719bc1c315d84acd52edd82170cad2c7dd`. Notice the `0x98` in the front, which is the length (152) of the remaining bytes. I believe it should be 
  ```go
  tx := encode(&sdk.TxVersion, &principal, &meta)
  tx = append(tx, payload...)
  ```

@brusherru 

Regarding decoding `980103f53f2080`, assuming that `98` is not there, `0103f53f20` stands for an _optional_ method selector. `01` means "present" and `03f53f20` is the selector for `athexp_spawn` method.

Complete TX payload is `0103f53f20803a5fba2aa0ee4e7414fad47d3ca57b85fbdc057a8b7643cc455d3d5fc438a304`, which is scale-encoded structure:
```rust
pub struct Payload {
  pub selector: Option<MethodSelector>,
  pub input: Vec<u8>,
}
```
Breaking it down:
| bytes    | explanation |
| -------- | ------- |
|01| "present" variant for `Option`|
|03f53f20| method selector|
|80|length of the `input Vec<u8>` (it's compact encoded so the value is 32, not 128)|
|3a5fba2aa0ee4e7414fad47d3ca57b85fbdc057a8b7643cc455d3d5fc438a304| `spawn()` input, which is [u8; 32]`

**Comment by brusherru** [comment]
> @brusherru you seem to misdecoded gas price. A compact-encoded gas price = 0x04 decodes to value 1, not 4 (see https://docs.substrate.io/reference/scale-codec/ there is exactly this example)

@poszu,
Yep, I know it. See my notes about version and gas price above. :)
Later I just separated actual bytes (in hex format) of encoded tx to the corresponding fields without decoding them.

But the rest is clear now.
Thanks for the explanation and pointing out on a proper method selectors!

**Comment by lrettig** [comment]
> * the method selector in the first column is created from wrong method names (`athcon_spawn/spend` instead of `athexp_spawn/spend`)

Thanks, fixed this.

> * The `payload` is already a `[]byte` and is scale-encoded for the second time

This is true, but unfortunately there's no way around the double-encoding without a redesign of how we process transactions. The `parse()` method in the VM receives _only_ a SCALE-decoder, which doesn't allow the reading of raw bytes. It _only_ allows decoding of SCALE-encoded data types. So it needs to "decode" the payload as a SCALE-encoded bytearray, even though it's already encoded. See https://github.com/spacemeshos/go-spacemesh/blob/363d39d7d4a24dd92f64f21397a99d29a9ac941b/vm/vm.go#L563.

Changing this would require either adding the capability of reading raw bytes to our SCALE implementation, or else handling the tx as raw bytes rather than as a SCALE decoder - but, then, we don't know where the SCALE-encoded portion ends and where the raw payload begins. It's messy, and I'm trying to make as few changes as possible for now to existing code.

**Comment by lrettig** [comment]
Attaching updated test vectors:

[vectors.txt](https://github.com/user-attachments/files/17591691/vectors.txt)

**Comment by brusherru** [comment]
Guys, another question.
How does the principal address is calculated?

It seems to me that we have changes here as well. Probably I misread the source code or there is a mistake in the vectors...

Tested on the first principal address and pubkey from the file:
PubKey: `f6bec05666f283c01f51ac9213d536dda6b80a8018cd8342c5deb710c49ebaaf`
Expected addr: `atest1qqqqqq9wtufvjrwactvggvkdhlmqcuu273ns0mgchjguw`

What I did:
1. Scale encode `{ compact: 0, compact: 0, bytes(32): pubkey }` following https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/core/hash.go#L31-L34
   Result: `[0, 0, 246, 190, 192, 86, 102, 242, 131, 192,  31, 81, 172, 146, 19, 213, 54, 221, 166, 184, 10, 128, 24, 205, 131, 66, 197, 222, 183, 16, 196, 158, 186, 175]`
2. Then prepended template address (24 bytes `[0, 0, ..., 0, 1]`)
    Result: `0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 246, 190, 192, 86, 102, 242, 131, 192, 31, 81, 172, 146, 19, 213, 54, 221, 166, 184, 10, 128, 24, 205, 131, 66, 197, 222, 183, 16, 196, 158, 186, 175` due to https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/core/hash.go#L20-L26
3. Calculated blake3 hash for it
    Result: `[169, 200, 67, 216, 38, 234, 13, 53, 40, 150, 248, 173, 48, 66, 85, 242, 18, 111, 80, 48, 200, 126, 215, 8]`
4. Take 20 bytes for that hash and append it to 4 zeroes
    Result: `[0, 0, 0, 0, 169, 200, 67, 216, 38, 234, 13, 53, 40, 150, 248, 173, 48, 66, 85, 242, 18, 111, 80, 48]` due to https://github.com/spacemeshos/go-spacemesh/blob/develop/common/types/address.go#L132-L139
5. Encode it with bech32 using HRP `atest`
    Result: `atest1qqqqqq9feppasfh2p56j39hc45cyy40jzfh4qvqq632ya`
    Expected: `atest1qqqqqq9wtufvjrwactvggvkdhlmqcuu273ns0mgchjguw`

I also tried the same approach that we're using in MainNet (without Nonce and Balance), tried using u64 codec instead of compact... and every time I'm getting different address than the expected one.

@poszu could you help please?

**Comment by lrettig** [comment]
> 1. Scale encode `{ compact: 0, compact: 0, bytes(32): pubkey }` following https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/core/hash.go#L31-L34
>    Result: `[0, 0, 246, 190, 192, 86, 102, 242, 131, 192,  31, 81, 172, 146, 19, 213, 54, 221, 166, 184, 10, 128, 24, 205, 131, 66, 197, 222, 183, 16, 196, 158, 186, 175]`

`Nonce` and `Balance` are encoded as u64, not compact. They require 8 bytes each.

https://github.com/spacemeshos/go-spacemesh/blob/athena-v1/vm/core/hash.go#L31-L34

**Comment by brusherru** [comment]
Ah, ok, it works.
I also took first bytes, while I need to take latest :)
Thanks!
